[package]
name = "brr64"
version = "0.1.0"
authors = ["ellcs"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = ["brr64-wasm"]

[dependencies]
regex = "1"
structopt = "0.3"
