name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install rust dependencies
      run: rustup target add wasm32-unknown-unknown
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Build wasm file for `docs`
      run: cargo build --target wasm32-unknown-unknown
    - name: Move compiled wasm32 file into `docs`
      run: |
        mv target/wasm32-unknown-unknown/debug/wasm_brr64.wasm docs/
        sed -i "s/COMMIT_HASH/$(git rev-parse --short HEAD)/" docs/index.html
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
