name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install rust dependencies
      run: rustup override set nightly && rustup target add wasm32-unknown-unknown && cargo install wasm-pack
    - name: Run tests
      run: cargo test --verbose
    - name: Build wasm file for `docs`
      run: cd brr64-wasm; wasm-pack build --target web; cd ..
    - name: Move compiled wasm32 file into `docs`
      run: |
        mkdir public
        mv brr64-wasm/pkg public/
        cp brr64-wasm/index.html public/
        sed -i "s/CURRENT_COMMIT_HASH/$(git rev-parse --short HEAD)/g" public/index.html
    - name: Deploy
      uses: ellcs/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
